# Site Specific Configuration
name: Daniel Chan 
description: A little website about me.
url: https://danielchan0305.github.io
author: Daniel Chan
timezone:  	Asia/Hong_Kong
timezone_short: HKT

# Keywords
keywords: ['computer science', 'programming', 'technology', 'hkust', 'jockey club', 'scholarship']

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

google_analytics:
  id: 'G-9H7729VEB6'

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 20
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

